# Generated by Django 5.2.5 on 2025-08-30 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='description',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
