version: '3.8'

services:
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - POSTGRES_DB=django_db
      - POSTGRES_USER=django_user
      - POSTGRES_PASSWORD=django_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U django_user"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    # Upewniamy się, że to entrypoint.sh uruchamia aplikację
    entrypoint: /usr/src/app/entrypoint.sh
    volumes:
      - ../:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: